//  fetchBalances
export const VAULT_FETCH_BALANCES_BEGIN = 'VAULT_FETCH_BALANCES_BEGIN';
export const VAULT_FETCH_BALANCES_SUCCESS = 'VAULT_FETCH_BALANCES_SUCCESS';
export const VAULT_FETCH_BALANCES_FAILURE = 'VAULT_FETCH_BALANCES_FAILURE';
//  fetchPoolBalances
export const VAULT_FETCH_POOL_BALANCES_BEGIN = 'VAULT_FETCH_POOL_BALANCES_BEGIN';
export const VAULT_FETCH_POOL_BALANCES_SUCCESS = 'VAULT_FETCH_POOL_BALANCES_SUCCESS';
export const VAULT_FETCH_POOL_BALANCES_FAILURE = 'VAULT_FETCH_POOL_BALANCES_FAILURE';
//  fetchApproval
export const VAULT_FETCH_APPROVAL_BEGIN = 'VAULT_FETCH_APPROVAL_BEGIN';
export const VAULT_FETCH_APPROVAL_SUCCESS = 'VAULT_FETCH_APPROVAL_SUCCESS';
export const VAULT_FETCH_APPROVAL_FAILURE = 'VAULT_FETCH_APPROVAL_FAILURE';
//  fetchFarmApporval
export const VAULT_FETCH_FARM_APPROVAL_BEGIN = 'VAULT_FETCH_FARM_APPROVAL_BEGIN';
export const VAULT_FETCH_FARM_APPROVAL_SUCCESS = 'VAULT_FETCH_FARM_APPROVAL_SUCCESS';
export const VAULT_FETCH_FARM_APPROVAL_FAILURE = 'VAULT_FETCH_FARM_APPROVAL_FAILURE';
//  fetchFarmAllowance
export const VAULT_FETCH_FARM_ALLOWANCE_BEGIN = 'VAULT_FETCH_FARM_ALLOWANCE_BEGIN';
export const VAULT_FETCH_FARM_ALLOWANCE_SUCCESS = 'VAULT_FETCH_FARM_ALLOWANCE_SUCCESS';
export const VAULT_FETCH_FARM_ALLOWANCE_FAILURE = 'VAULT_FETCH_FARM_ALLOWANCE_FAILURE';
//  fetchFarmAllowance
export const VAULT_FETCH_FARM_CLAIM_BEGIN = 'VAULT_FETCH_FARM_CLAIM_BEGIN';
export const VAULT_FETCH_FARM_CLAIM_SUCCESS = 'VAULT_FETCH_FARM_CLAIM_SUCCESS';
export const VAULT_FETCH_FARM_CLAIM_FAILURE = 'VAULT_FETCH_FARM_CLAIM_FAILURE';
//  fetchFarmsStaked
export const VAULT_FETCH_FARMS_STAKED_BEGIN = 'VAULT_FETCH_FARMS_STAKED_BEGIN';
export const VAULT_FETCH_FARMS_STAKED_SUCCESS = 'VAULT_FETCH_FARMS_STAKED_SUCCESS';
export const VAULT_FETCH_FARMS_STAKED_FAILURE = 'VAULT_FETCH_FARMS_STAKED_FAILURE';
//  fetchFarmStake
export const VAULT_FETCH_FARM_STAKE_BEGIN = 'VAULT_FETCH_FARM_STAKE_BEGIN';
export const VAULT_FETCH_FARM_STAKE_SUCCESS = 'VAULT_FETCH_FARMS_STAKE_SUCCESS';
export const VAULT_FETCH_FARM_STAKE_FAILURE = 'VAULT_FETCH_FARMS_STAKE_FAILURE';
//  fetchFarmUnstake
export const VAULT_FETCH_FARM_UNSTAKE_BEGIN = 'VAULT_FETCH_FARM_UNSTAKE_BEGIN';
export const VAULT_FETCH_FARM_UNSTAKE_SUCCESS = 'VAULT_FETCH_FARMS_UNSTAKE_SUCCESS';
export const VAULT_FETCH_FARM_UNSTAKE_FAILURE = 'VAULT_FETCH_FARMS_UNSTAKE_FAILURE';
//  fetchDeposit
export const VAULT_FETCH_DEPOSIT_BEGIN = 'VAULT_FETCH_DEPOSIT_BEGIN';
export const VAULT_FETCH_DEPOSIT_SUCCESS = 'VAULT_FETCH_DEPOSIT_SUCCESS';
export const VAULT_FETCH_DEPOSIT_FAILURE = 'VAULT_FETCH_DEPOSIT_FAILURE';
//  fetchWithdraw
export const VAULT_FETCH_WITHDRAW_BEGIN = 'VAULT_FETCH_WITHDRAW_BEGIN';
export const VAULT_FETCH_WITHDRAW_SUCCESS = 'VAULT_FETCH_WITHDRAW_SUCCESS';
export const VAULT_FETCH_WITHDRAW_FAILURE = 'VAULT_FETCH_WITHDRAW_FAILURE';
//  fetchPancakeswapPrices
export const VAULT_FETCH_CONTRACT_APY_BEGIN = 'VAULT_FETCH_CONTRACT_APY_BEGIN';
export const VAULT_FETCH_CONTRACT_APY_SUCCESS = 'VAULT_FETCH_CONTRACT_APY_SUCCESS';
export const VAULT_FETCH_CONTRACT_APY_FAILURE = 'VAULT_FETCH_CONTRACT_APY_FAILURE';
// fetchClaim
export const VAULT_FETCH_CLAIM_BEGIN = 'VAULT_FETCH_CLAIM_BEGIN';
export const VAULT_FETCH_CLAIM_SUCCESS = 'VAULT_FETCH_CLAIM_SUCCESS';
export const VAULT_FETCH_CLAIM_FAILURE = 'VAULT_FETCH_CLAIM_FAILURE';
// fetchPendingRewards
export const VAULT_FETCH_PENDING_REWARDS_BEGIN = 'VAULT_FETCH_PENDING_REWARDS_BEGIN';
export const VAULT_FETCH_PENDING_REWARDS_SUCCESS = 'VAULT_FETCH_PENDING_REWARDS_SUCCESS';
export const VAULT_FETCH_PENDING_REWARDS_FAILURE = 'VAULT_FETCH_PENDING_REWARDS_FAILURE';
// fetchPoolRewards
export const VAULT_FETCH_POOL_REWARDS_BEGIN = 'VAULT_FETCH_POOL_REWARDS_BEGIN';
export const VAULT_FETCH_POOL_REWARDS_SUCCESS = 'VAULT_FETCH_POOL_REWARDS_SUCCESS';
export const VAULT_FETCH_POOL_REWARDS_FAILURE = 'VAULT_FETCH_POOL_REWARDS_FAILURE';
// fetchFilters
export const VAULT_FILTERS_SET_CATEGORIES = 'VAULT_FILTERS_SET_CATEGORIES';
export const VAULT_FILTERS_SET_WITH_BALANCE = 'VAULT_FILTERS_SET_WITH_BALANCE';
export const VAULT_FILTERS_SET_DEPOSITED = 'VAULT_FILTERS_SET_DEPOSITED';
export const VAULT_FILTERS_SET_SEARCH_PHRASE = 'VAULT_FILTERS_SET_SEARCH_PHRASE';
export const VAULT_FILTERS_SET_SORT = 'VAULT_FILTERS_SET_SORT';